const DUBLICATE_MONGOOSE_ERROR_CODE = 11000;
const HTTP_CREATE = 201;
const SALT_ROUNDS = 10;
const { SECRET_KEY } = process.env;

module.exports = {
  DUBLICATE_MONGOOSE_ERROR_CODE,
  SALT_ROUNDS,
  SECRET_KEY,
  HTTP_CREATE,
};
